### ISSUE TITLE
As STA Green Mobility I would like that the e-mobility web-components also show static charging datasets

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-dashboard#63]
Linked to https://github.com/noi-techpark/bdp-commons/issues/582

We need to check these web-components, if they include this additional data in their views:
- [x] https://webcomponents.opendatahub.com/webcomponent/mobility-e-charging-dashboard?from=%2F
- [x] https://webcomponents.opendatahub.com/webcomponent/mobility-e-charging-map?from=%2F

**Comment by rcavaliere** [comment]
PS: on analytics data is visualized as expected

**Comment by clezag** [comment]
@rcavaliere 
Dashboard now works (#64), I've had to move some metadata from the Plug to the Station, so that it conforms to existing data (and what the webcomponent expects).

The Map web component on the other hand still does not display the new stations:
It currently expects measurements of type "number-available" to exist. If the station does not have any measurement, it is not considered (not even requested from the API).
We can go two ways:
- Add a default measurement and capacity of 1 to every station (or define a column capacity and use that). Those stations will always show up as "green" available
- Modify the web component to handle stations without measurements, possibly show a disclaimer that we don't have any data about availability

**Comment by rcavaliere** [comment]
@clezag I would go for option nr. 2, but let's discuss this tomorrow in our Sprint Meeting. I think we need also to change a little bit the application in terms of UX / UI

**Comment by rcavaliere** [comment]
@clezag I have thought a little bit on the different options here. I would go for option 2, definitely. We have to avoid to insert "artifact" data that be could be misunderstood. My proposal would simply be:
 - [ ] show static charging data differently (e.g. with grey icon)
 - [ ] add a filter possibility to disable the visualization of just this data (e.g. "Only real-time charging stations")
 - [ ] ensure that these charging stations are properly visualized if one of the other existing filters are activated (e.g. if static charging station supports CCS and CCS filter is activated -> this static charging station is visualized).

**Comment by clezag** [comment]
Just an update: The dashboard webcomponent has the same issue: The new stations show up in the access type chart, but not in the state chart. 
The difference in total stations between the two is 19, which is the number of stations in the spreadsheet.

As with the web component, all charts besides the access type use API calls that request measurements, and since there are none for these new stations, they are not present in the returned list.

**Comment by rcavaliere** [comment]
@clezag wonderful! How are static charging stations visualized on the dashboard, as access state = UNKNOWN?

**Comment by clezag** [comment]
@rcavaliere Yes, as long the station state (pmetadata.state - should map to column STATE in the spreadsheet) is one of the active states, the plug status is counted as unknown. 

If the station state is "FAULT" or "TEMPORARYUNAVAILABLE",  the station and it's plugs will be counted as "not operational"

**Comment by clezag** [comment]
@rcavaliere I've released a new version of the map webcomponent in testing.
The new stations and plugs are now visible on the map.

The new requirements above, like special handling of the "unknown" state, differently colored icons, filters etc. are not yet implemented. Currently the stations are always green and the plugs always red, this is just how the existing logic deals with missing values.

I've noted that the format in which we store plugs (all outlet types under one plug vs one plug per outlet type) is different in regards to the other data.

The provider search depends on metadata.provider, which we currently do not set in the data collector, I guess we could just map the column "DATA_PROVIDER" to it.

**Comment by clezag** [comment]
@rcavaliere I've implemented most of the requested features, the new build is up in testing:
- New turquoise map icon for static charging stations
- New grey question mark icon for plugs without data
- Added disclaimer about missing real time data in detail view
- Added filter for real time stations only
- Changed the google maps link German description from "Richtungen" to "Wegbeschreibung" 

In particular, I'd love some feedback on the Icons. I've tried turquoise, because it's still somewhat green (after all, these stations should be available most of the time), and blue is already used for H2 charging stations, though there are currently none active.
I'm not too happy with the grey plug Icon, because grey is used throughout the app to denote something inactive. Maybe it scares off potential users?

The turquoise lock and star icons for static stations (private and private with public access) are still missing, as I'd first like to finalize the color before creating them.

Regarding the new filter: The old "only available stations" also filters out the static stations, so in my opinion in the current form they are a bit redundant and take up valuable space

**Comment by rcavaliere** [comment]
@clezag I like the color of the icon and the filter for real-time only! I couldn't find an example of the second feature (grey question mark), can you make me an example here? For the data provider comment above, yes, do it like you said, so that they are also visible in the filter view

**Comment by clezag** [comment]
It's this icon here:
![image](https://user-images.githubusercontent.com/48801473/228143286-37f24980-037b-444e-8fcc-cbc53ada87aa.png)
But I guess if you didn't catch it, it wasn't that confusing after all :smile: 

I've added the provider field to the station metadata, and the filter now works as expected.

**Comment by clezag** [comment]
@rcavaliere I'v added the missing icons (lock and star - depending on access_type) as well.
I think with that everything is implemented.
Let me know when I can go ahead and deploy in production

**Comment by rcavaliere** [comment]
@clezag very good work! For the grey icon, I don't feel this so problematic. Before going into production, I would like to hear the feedback of STA Green Mobility, who gave us the commitment for initial development of these web-components. In the meantime let's put this under "blocked" but ready for production

**Comment by rcavaliere** [comment]
Feedback STA: very good, maybe in the map we should add a legend in order to explain the new icon. In my view, this should be another user story. This new web components version can go online (after Eastern :-))

![Screenshot from 2023-04-06 16-49-57](https://user-images.githubusercontent.com/9825179/230416459-0c6339fa-16f2-4d8e-adf4-36bcfaa2c475.png)

**Comment by clezag** [comment]
@rcavaliere Changes are now released in production
